### ISSUE TITLE
Support awspfx with python 3.9

### ISSUE THREAD

**Issue by jhonnatangilappgate** [marioapardo/awspfx#3]
Replace docopt for docopt-ng

in pyproject.toml
docopt-ng = "^0.7.2"
#docopt = "^0.6.2"

pyproject.toml
[tool.poetry.dependencies]
python = "^3.7 || ^3.8"
boto3 = "^1.14.50"
iterfzf = "^0.5.0"
colorlog = "^4.2.1"
docopt-ng = "^0.7.2"
#docopt = "^0.6.2"

And
requirements.txt
boto3==1.14.51
botocore==1.17.51
colorlog==4.2.1
#docopt>=0.6.2
docopt-ng>=0.7.2

With this changes will supported Python3.9 for this amazing tool!! 

Thanks!!

**Comment by marioapardo** [comment]
:thanks:
